#!/bin/bash

PRGNAM=lxde-common

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

git clone https://github.com/lxde/${PRGNAM}
cd ${PRGNAM}
VERSION=`git describe | cut -d- -f1`

./autogen.sh

CFLAGS="$GCC_CFLAGS" \
./configure \
	--prefix=/usr \
	--libdir=/usr/lib$SYSTEM_BITS \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--enable-gtk3 \
	--disable-static \
	--disable-man

make -j${NUMBER_THREADS} install-strip DESTDIR=$PKG

find $PKG -type f -name "*.la" -delete
rm $PKG/usr/share/lxde/wallpapers/lxde_green.jpg
rm $PKG/usr/share/lxde/wallpapers/lxde_red.jpg

sed -i "s|Onyx|Porteux|g" $PKG/etc/xdg/openbox/LXDE/rc.xml

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz