#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=cosmic-greeter

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(download_master_from_github pop-os $PRGNAM) || exit 1
cd $PRGNAM-master || exit 1

for i in $CWD/*.patch; do
	patch -p0 < $i
done

ls rust-toolchain* 1> /dev/null 2>&1 && rm rust-toolchain*
just build-release --target x86_64-unknown-linux-gnu
cp -aln ./target/x86_64-unknown-linux-gnu/release ./target/
just rootdir=$PKG install

install -Dm644 debian/"$PRGNAM"-daemon.service "$PKG/usr/share/dbus-1/system-services/com.system76.CosmicGreeter.service"
install -Dm644 "$CWD/cosmic-greeter" $PKG/etc/pam.d/cosmic-greeter

mkdir -p $PKG/var/lib/cosmic-greeter/
chown 600:600 $PKG/var/lib/cosmic-greeter

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-${ARCH}-1_porteux.txz
