#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=dart-sass

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

versions=$(get_latest_versions_tag_from_github "sass" ${PRGNAM} "sass")

for VERSION in ${versions}; do
	wget https://github.com/sass/${PRGNAM}/releases/download/${VERSION}/${PRGNAM}-${VERSION}-linux-x64.tar.gz && break
done

tar xf ${PRGNAM}-${VERSION}-linux-x64.tar.?z

mkdir -p $PKG/usr/bin
cp -r ${PRGNAM}/* $PKG/usr/bin

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz