#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=mate-search-tool

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "mate-desktop" "mate-utils" "1.29")
VERSION=${info#* }

tar xf mate-utils-$VERSION.tar.?z
cd mate-utils-$VERSION

patch -p0 < $CWD/configure.ac.patch

sed -i 's|baobab||g' ./Makefile.am
sed -i 's|mate-dictionary||g' ./Makefile.am
sed -i 's|mate-screenshot||g' ./Makefile.am
sed -i 's|logview||g' ./Makefile.am
sed -i 's|yelp-build|ls|g' autogen.sh
sed -i 's|dnl yelp-tools stuff||g' configure.ac
sed -i 's|YELP_HELP_INIT||g' configure.ac
sed -i 's| help||g' gsearchtool/Makefile.am
sed -i 's|readable_size = g_format_size (g_file_info_get_size (file_info))|readable_size = g_format_size_full (g_file_info_get_size (file_info), G_FORMAT_SIZE_IEC_UNITS)|g' gsearchtool/src/gsearchtool.c

CFLAGS="$GCC_CFLAGS -ffat-lto-objects" \
./autogen.sh \
	--prefix=/usr \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--sysconfdir=/etc \
	--disable-static \
	--disable-debug \
	--disable-gdict-applet \
	--disable-disk-image-mounter \
	--disable-gtk-doc-html

make -j${NUMBER_THREADS} install-strip DESTDIR=$PKG

wget https://raw.githubusercontent.com/mate-desktop/mate-desktop/v$VERSION/schemas/org.mate.interface.gschema.xml -P $PKG/usr/share/glib-2.0/schemas

find $PKG -type f -name "*.la" -delete

sed -z -i "s|OnlyShowIn=MATE;\\n||g" $PKG/usr/share/applications/mate-search-tool.desktop
sed -i "s|MATE;||g" $PKG/usr/share/applications/mate-search-tool.desktop
sed -i "s|MATE ||g" $PKG/usr/share/applications/mate-search-tool.desktop
sed -i "s| MATE||g" $PKG/usr/share/applications/mate-search-tool.desktop

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz