#!/bin/bash

PRGNAM=gnome-browser-connector

CWD=$(dirname "$0")
TMP=$MODULEPATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

wget https://gitlab.gnome.org/GNOME/${PRGNAM}/-/archive/master/${PRGNAM}-master.tar.gz
tar xf ${PRGNAM}-master.tar.?z*
cd ${PRGNAM}-master
VERSION=$(date -r . +%Y%m%d)

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS" \
meson setup \
	--prefix=/usr \
	--buildtype=release \
	--libdir=/usr/lib${SYSTEMBITS} \
	--libexecdir=/usr/libexec \
	--sysconfdir=/etc \
	--localstatedir=/var

DESTDIR=$PKG ninja -j${NUMBERTHREADS} install

find $PKG -type f -name "*.la" -exec rm -f {} \;

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKGFLAGS} $MODULEPATH/packages/${PRGNAM}-${VERSION//v/}-$ARCH-1_porteux.txz
