#!/bin/bash

PRGNAM=libsysstat

CWD=$(dirname "$0")
TMP=$MODULE_PATH/${PRGNAM}
PKG=$TMP/package-${PRGNAM}

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

wget https://github.com/lxqt/libsysstat/archive/refs/heads/master.tar.gz -O ${PRGNAM}.tar.gz
tar xf ${PRGNAM}.tar.gz
cd libsysstat-master
VERSION=$(date -r . +%Y%m%d)

cmake -B build -S . \
	-DCMAKE_BUILD_TYPE=release \
	-DCMAKE_CXX_FLAGS="$GCC_CXXFLAGS" \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=lib${SYSTEM_BITS}

make -C build -j${NUMBER_THREADS} DESTDIR="$PKG" install

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/${PRGNAM}-$VERSION-$ARCH-1_porteux.txz