#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=pamixer

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "cdemoulins" ${PRGNAM})
VERSION=${info#* }

tar xf $PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION

mkdir meson-build && cd meson-build
CC=clang \
CXX=clang++ \
CFLAGS="$CLANG_CFLAGS" \
CXXFLAGS="$CLANG_CXXFLAGS" \
LDFLAGS="$LLDFLAGS" \
meson setup \
	--prefix=/usr \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--libexecdir=/usr/libexec \
	--bindir=/usr/bin \
	--sbindir=/usr/sbin \
	--includedir=/usr/include \
	--datadir=/usr/share \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--buildtype=release 

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -exec rm -f {} \;

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz