#!/bin/bash

PRGNAM=xdg-desktop-portal-cosmic

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

git clone https://github.com/pop-os/$PRGNAM
cd $PRGNAM
VERSION=$(git log -1 --date=format:"%Y%m%d" --format="%ad")

RUSTFLAGS="${RUSTFLAGS/-Clto=fat/}"

ls rust-toolchain* 1> /dev/null 2>&1 && rm rust-toolchain*
CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu just build
rsync -r ./target/x86_64-unknown-linux-gnu/release ./target/ --remove-source-files
just rootdir=$PKG install

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-${ARCH}-1_porteux.txz
