#!/bin/bash

PRGNAM=localsearch

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(curl -s https://gitlab.gnome.org/GNOME/${PRGNAM}/-/tags?format=atom | grep -oPm 20 '(?<= <title>)[^<]+' | eval "${TEST_RELEASES:-sort -Vr}" | head -1)
wget https://gitlab.gnome.org/GNOME/${PRGNAM}/-/archive/${VERSION}/${PRGNAM}-${VERSION}.tar.gz
[ ! -s ${PRGNAM}-${VERSION}.tar.gz ] && wget https://github.com/GNOME/${PRGNAM}/archive/refs/tags/$VERSION.tar.gz -O $PRGNAM-$VERSION.tar.gz

tar xf $PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION

for i in $CWD/*.patch; do
	patch -p1 < $i
done

sed -i "s|subdir('docs')|#subdir('docs')|g" meson.build
sed -i "s|subdir('tests')|#subdir('tests')|g" meson.build
sed -i "s|subdir('examples')|#subdir('examples')|g" meson.build
sed -i "s|run_uninstalled_conf.set('tracker_uninstalled_miner|#run_uninstalled_conf.set('tracker_uninstalled_miner|g" meson.build
sed -i "s|run_uninstalled_conf.set('tracker_uninstalled_testutils|#run_uninstalled_conf.set('tracker_uninstalled_testutils|g" meson.build

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS" \
meson setup \
	--buildtype=release \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--localstatedir=/var \
	--prefix=/usr \
	--sysconfdir=/etc \
	-Dstrip=true \
	-Dman=false \
	-Dfunctional_tests=false \
	-Dsandbox_tests=false \
	-Dlandlock=disabled \
	-Dwriteback=false \
	-Dseccomp=false \
	-Dsystemd_user_services=false \
	-Dbash_completion=false \
	-Dbattery_detection=none \
	-Dtests_tap_protocol=false \
	-Dunzip_ps_gz_files=false

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -exec rm -f {} \;
rm $PKG/usr/share/dbus-1/services/org.freedesktop.LocalSearch3.Control.service
rm $PKG/usr/share/dbus-1/services/org.freedesktop.LocalSearch3.service
rm $PKG/usr/share/dbus-1/services/org.freedesktop.Tracker3.Miner.Files.Control.service
rm $PKG/usr/share/dbus-1/services/org.freedesktop.Tracker3.Miner.Files.service

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/${PRGNAM}-$VERSION-$ARCH-1_porteux.txz