#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=dash-to-dock

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(download_master_from_github micheleg dash-to-dock) || exit 1
cd dash-to-dock-master || exit 1

for i in $CWD/*.patch; do
	patch -p0 < $i
done

make -j${NUMBER_THREADS} DESTDIR=${PKG} VERSION=$VERSION install

EXTENSIONPATH="usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com"

rm $PKG/${EXTENSIONPATH}/COPYING
rm $PKG/${EXTENSIONPATH}/README.md

mv $PKG/usr/share/glib-2.0/schemas $PKG/${EXTENSIONPATH}/
rm -fr $PKG/usr/share/glib-2.0
glib-compile-schemas $PKG/${EXTENSIONPATH}/schemas/

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/${PRGNAM}-$VERSION-$ARCH-1_porteux.txz
