#!/bin/bash

PRGNAM=xfce4-appfinder

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

DOWNLOADVERSION=$(curl -s https://gitlab.xfce.org/xfce/${PRGNAM}/-/tags?format=atom | grep -oPm 20 '(?<= <title>)[^<]+' | grep -Ev '^xfce-|pre' | sort -Vr | {
	if [[ "$ALLOW_TEST" == "yes" ]]; then
		head -1
	else
		while read -r version; do
			minor=$(echo "$version" | cut -d. -f2)
			if (( minor % 2 == 0 )); then
				echo "$version"
				break
			fi
		done
	fi
})
if [ -z "$DOWNLOADVERSION" ]; then
	echo "Error: cannot detect latest $PRGNAM version."
	exit 1
fi
VERSION=$(echo $DOWNLOADVERSION | rev | cut -d '-' -f 1 | rev)
wget https://gitlab.xfce.org/xfce/${PRGNAM}/-/archive/${DOWNLOADVERSION}/${PRGNAM}-${DOWNLOADVERSION}.tar.gz

tar xf $PRGNAM-$DOWNLOADVERSION.tar.?z*
cd $PRGNAM-$DOWNLOADVERSION

# fix runner not executing apps with single Enter stroke
for i in $CWD/*.patch; do
	patch -p1 < $i
done

# add support to case insensitive match
sed -i 's/xfce_appfinder_model_fuzzy_match (item->command, string);/strcasestr(item->command, string) != 0;/g' src/appfinder-model.c
grep -q 'strcasestr(item->command, string)' src/appfinder-model.c

# add support to 'contains' match
if grep -q 'item->key_basic' src/appfinder-model.c; then
	sed -i 's/ || xfce_appfinder_model_fuzzy_match (item->key_basic, string_casefold)//g' src/appfinder-model.c
	grep -q 'regular_match (item->key_basic, item->key_extended, string_casefold);' src/appfinder-model.c
else
	sed -i 's/xfce_appfinder_model_fuzzy_match (item->key, string_casefold);/strcasestr(item->key, string_casefold) != 0;/g' src/appfinder-model.c
	grep -q 'strcasestr(item->key, string_casefold)' src/appfinder-model.c
fi

if [ -f meson.build ]; then
	mkdir meson-build && cd meson-build
	CFLAGS="$GCC_CFLAGS" \
	meson setup \
		--prefix=/usr \
		--buildtype=release \
		--libdir=/usr/lib${SYSTEM_BITS} \
		--libexecdir=/usr/libexec \
		--sysconfdir=/etc \
		--localstatedir=/var

	DESTDIR=$PKG ninja -j${NUMBER_THREADS} install
else
	CFLAGS="$GCC_CFLAGS" \
	./autogen.sh \
		--prefix=/usr \
		--libdir=/usr/lib${SYSTEM_BITS} \
		--sysconfdir=/etc \
		--disable-static \
		--disable-debug \
		--build=$ARCH-porteux-linux

	make -j${NUMBER_THREADS} install-strip DESTDIR=$PKG
fi

find $PKG -type f -name "*.la" -delete

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
