#!/bin/bash

PRGNAM=nm-tray

CWD=$(dirname "$0")
TMP=$MODULEPATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

wget https://github.com/palinek/nm-tray/archive/refs/heads/master.tar.gz -O ${PRGNAM}.tar.gz
tar xf ${PRGNAM}.tar.gz
cd nm-tray-master
VERSION=$(date -r . +%Y%m%d)

cmake -B build -S . \
	-DCMAKE_BUILD_TYPE=release \
	-DCMAKE_CXX_FLAGS="$GCC_CXXFLAGS" \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=lib${SYSTEMBITS} \
	-DCMAKE_INSTALL_SYSCONFDIR=/etc

make -C build -j${NUMBERTHREADS} DESTDIR="$PKG" install

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKGFLAGS} $MODULEPATH/packages/${PRGNAM}-$VERSION-$ARCH-1_porteux.txz