#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=nm-tray

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(download_master_from_github palinek nm-tray) || exit 1
cd nm-tray-master || exit 1

cmake -B build -S . \
	-DCMAKE_BUILD_TYPE=release \
	-DCMAKE_CXX_FLAGS="$GCC_CXXFLAGS" \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=lib${SYSTEM_BITS} \
	-DCMAKE_INSTALL_SYSCONFDIR=/etc

make -C build -j${NUMBER_THREADS} DESTDIR="$PKG" install

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/${PRGNAM}-$VERSION-$ARCH-1_porteux.txz