#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=yaru-icon-theme

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(download_master_from_github ubuntu yaru) || exit 1
cd yaru-master || exit 1

rm -fr icons/Yaru/cursor*
rm -fr icons/Yaru/scalable-max-32
rm -fr icons/Yaru/*@2x
rm -fr icons/Yaru-blue/*@2x

mainIconRootFolder=$PKG/usr/share/icons/Yaru
blueIconRootFolder=$PKG/usr/share/icons/Yaru-blue
mkdir -p $mainIconRootFolder
mkdir -p $blueIconRootFolder
cp -r icons/Yaru/* $mainIconRootFolder
cp -r icons/Yaru-blue/* $blueIconRootFolder
install -Dm644 "$CWD/index.theme" $mainIconRootFolder
install -Dm644 "$CWD/index-blue.theme" $blueIconRootFolder/index.theme
gtk-update-icon-cache -f $mainIconRootFolder
gtk-update-icon-cache -f $blueIconRootFolder

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-noarch-1_porteux.txz > /dev/null 2>&1