#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=muffin

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "linuxmint" ${PRGNAM} "${TESTRELEASES}")
VERSION=${info#* }

tar xf $PRGNAM-$VERSION*.tar.?z
cd $PRGNAM-$VERSION*/

sed -i "s|subdir('doc/man')|#subdir('doc/man')|g" meson.build

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS -Wno-incompatible-pointer-types" \
meson setup \
	--buildtype=release \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--localstatedir=/var \
	--prefix=/usr \
	--sysconfdir=/etc \
	-Dstrip=true \
	-Dprofiler=false \
	-Dwayland=true \
	-Dnative_backend=true \
	-Dcogl_tests=false \
	-Dclutter_tests=false \
	-Dcore_tests=false \
	-Dtests=false \
	-Dremote_desktop=false \
	-Degl_device=false \
	-Dwayland_eglstream=false \
	-Dlibwacom=false \
	-Dinstalled_tests=false

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -exec rm -f {} \;

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
