#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=7zip

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

uasmVersion=2.57
wget https://github.com/Terraspace/UASM/archive/refs/tags/v${uasmVersion}r.tar.gz -O UASM-${uasmVersion}r.tar.gz

tar xf UASM-${uasmVersion}r.tar.?z*
cd UASM-${uasmVersion}r

make -j${NUMBER_THREADS} CC="gcc $GCC_CFLAGS -std=c99 -fcommon -Wno-implicit-function-declaration -Wno-incompatible-pointer-types -Wno-int-conversion -Wno-discarded-qualifiers -Wno-lto-type-mismatch -Wno-compare-distinct-pointer-types -Wno-pointer-to-int-cast" -f Makefile-Linux-GCC-64.mak

chmod +x $PWD/GccUnixR/uasm
PATH=$PATH:$PWD/GccUnixR
cd ..

info=$(download_latest_from_github "ip7z" ${PRGNAM})
VERSION=${info#* }

tar xf $PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION

cp "$CWD/meson.build.template" meson.build
meson rewrite kwargs set project / version ${VERSION}

mkdir meson-build && cd meson-build
CFLAGS="${GCC_CFLAGS/-fipa-reorder-for-locality/} -pthread" \
CXXFLAGS="${GCC_CXXFLAGS/-fipa-reorder-for-locality/} -pthread" \
meson setup \
	--prefix=/usr \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--libexecdir=/usr/libexec \
	--bindir=/usr/bin \
	--sbindir=/usr/sbin \
	--includedir=/usr/include \
	--datadir=/usr/share \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--buildtype=release

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -delete
rm -fr $PKG/usr/share/doc

cd $PKG/usr/bin
cp -s 7zz 7z

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
