#!/bin/bash

PRGNAM=thunar

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

DOWNLOADVERSION=$(curl -s https://gitlab.xfce.org/xfce/${PRGNAM}/-/tags?format=atom | grep -oPm 20 '(?<= <title>)[^<]+' | grep -Ev '^xfce-|pre' | sort -Vr | {
	if [[ "$ALLOW_TEST" == "yes" ]]; then
		head -1
	else
		while read -r version; do
			minor=$(echo "$version" | cut -d. -f2)
			if (( minor % 2 == 0 )); then
				echo "$version"
				break
			fi
		done
	fi
})
VERSION=$(echo $DOWNLOADVERSION | rev | cut -d '-' -f 1 | rev)
wget https://gitlab.xfce.org/xfce/${PRGNAM}/-/archive/${DOWNLOADVERSION}/${PRGNAM}-${DOWNLOADVERSION}.tar.gz

tar xf $PRGNAM-$DOWNLOADVERSION.tar.?z*
cd $PRGNAM-$DOWNLOADVERSION

if [ -f meson.build ]; then
	mkdir meson-build && cd meson-build
	CFLAGS="$GCC_CFLAGS -ffat-lto-objects" \
	meson setup \
		--prefix=/usr \
		--buildtype=release \
		--libdir=/usr/lib${SYSTEM_BITS} \
		--libexecdir=/usr/libexec \
		--sysconfdir=/etc \
		--localstatedir=/var \
		-Dintrospection=false \
		-Dgtk-doc=false \
		-Dtests=false

	DESTDIR=$PKG ninja -j${NUMBER_THREADS} install
else
	CFLAGS="$GCC_CFLAGS -ffat-lto-objects" \
	./autogen.sh \
		--prefix=/usr \
		--libdir=/usr/lib${SYSTEM_BITS} \
		--sysconfdir=/etc \
		--disable-static \
		--disable-debug \
		--disable-introspection \
		--build=$ARCH-porteux-linux

	make -j${NUMBER_THREADS} install-strip DESTDIR=$PKG
fi

find $PKG -type f -name "*.la" -delete
rm -fr $PKG/usr/share/man
rm -fr $PKG/usr/share/Thunar

sed -i "s|Categories=System;|Categories=|g" $PKG/usr/share/applications/thunar.desktop
sed -i "s|System;||g" $PKG/usr/share/applications/thunar-bulk-rename.desktop

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
