#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=polkit

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "polkit-org" ${PRGNAM})
VERSION=${info#* }

tar xf $PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION

patch -p1 < $CWD/dont-set-wheel-group-as-admin.patch

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS" \
meson setup \
	--prefix=/usr \
	--libdir=lib${SYSTEM_BITS} \
	--libexecdir=/usr/libexec \
	--bindir=/usr/bin \
	--sbindir=/usr/sbin \
	--includedir=/usr/include \
	--datadir=/usr/share \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--buildtype=release \
	-Dsession_tracking=elogind \
	-Dsystemdsystemunitdir=/usr/lib/systemd/user \
	-Dauthfw=pam \
	-Dpam_module_dir=/lib${SYSTEM_BITS}/security \
	-Dpam_prefix=/etc/pam.d \
	-Dexamples=false \
	-Dgtk_doc=false \
	-Dman=false \
	-Dtests=false

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/${PRGNAM}-$VERSION-$ARCH-1_porteux.txz
