#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=mpv

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "mpv-player" ${PRGNAM})
VERSION=${info#* }

tar xf $PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION

mkdir meson-build && cd meson-build
CC=clang \
CFLAGS="$CLANG_CFLAGS" \
LDFLAGS="$LLDFLAGS" \
meson setup \
	--prefix=/usr \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--sysconfdir=/etc \
	-Dbuildtype=release \
	-Dmanpage-build=disabled \
	-Dlibmpv=false \
	-Dhtml-build=disabled \
	-Dcdda=enabled \
	-Ddvdnav=enabled \
	-Ddvbin=enabled \
	-Dvulkan=enabled \
	-Dshaderc=disabled \
	-Dlua=luajit \
	-Dpipewire=auto \
	-Dcaca=disabled \
	-Dtests=false

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -delete
rm -fr $PKG/usr/share/bash-completion
rm -fr $PKG/usr/share/doc
rm -fr $PKG/usr/share/fish
rm -fr $PKG/usr/share/zsh

sed -i "s|TryExec=.*||g" $PKG/usr/share/applications/mpv.desktop
sed -i "s|Exec=.*|Exec=mpv --player-operation-mode=pseudo-gui --hwdec=auto --no-osd-bar --audio-file-auto=fuzzy -- %U|g" $PKG/usr/share/applications/mpv.desktop

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
