#!/bin/bash

PRGNAM=cosmic-term

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

git clone --depth 1 https://github.com/pop-os/$PRGNAM
cd $PRGNAM
VERSION=$(git log -1 --date=format:"%Y%m%d" --format="%ad")

sed -i "s|license = {|#license = {|g" Cargo.toml

ls rust-toolchain* 1> /dev/null 2>&1 && rm rust-toolchain*
just build-release --target x86_64-unknown-linux-gnu
cp -al ./target/x86_64-unknown-linux-gnu/release ./target/
just rootdir=$PKG install

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-${ARCH}-1_porteux.txz
