#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=intel-media-driver

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "intel" "media-driver")
VERSION=${info#* }

tar xf *.tar.?z
cd media-driver-intel-media-${VERSION}

for i in $CWD/*.patch; do
	patch -p1 < $i
done

cmake -B build -S . \
	-G Ninja \
	-DCMAKE_C_FLAGS="$GCC_CFLAGS" \
	-DCMAKE_CXX_FLAGS="$GCC_CXXFLAGS" \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=lib${SYSTEM_BITS} \
	-DCMAKE_INSTALL_BINDIR=/usr/bin \
	-DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
	-DMEDIA_BUILD_FATAL_WARNINGS=OFF \
	-DCMAKE_BUILD_TYPE="Release"

DESTDIR=$PKG ninja -C build -j${NUMBER_THREADS} install

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
