#!/bin/bash

PRGNAM=vte

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(curl -s https://gitlab.gnome.org/GNOME/${PRGNAM}/-/tags?format=atom | grep -oPm 20 '(?<= <title>)[^<]+' | sort -Vr | {
	if [[ "$ALLOW_TEST" == "yes" ]]; then
		head -1
	else
		while read -r version; do
			minor=$(echo "$version" | cut -d. -f2)
			if (( minor % 2 == 0 )); then
				echo "$version"
				break
			fi
		done
	fi
})
wget https://gitlab.gnome.org/GNOME/${PRGNAM}/-/archive/${VERSION}/${PRGNAM}-${VERSION}.tar.gz
[ ! -s ${PRGNAM}-${VERSION}.tar.gz ] && wget https://github.com/GNOME/${PRGNAM}/archive/refs/tags/$VERSION.tar.gz -O $PRGNAM-$VERSION.tar.gz

tar xf $PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS" \
CXXFLAGS="$GCC_CXXFLAGS" \
meson setup \
	--prefix=/usr \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--libexecdir=/usr/libexec \
	--bindir=/usr/bin \
	--sbindir=/usr/sbin \
	--includedir=/usr/include \
	--datadir=/usr/share \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--buildtype=release \
	-Dgtk3=false \
	-D_systemd=false \
	-Dicu=false \
	-Ddocs=false \
	-Dgir=false \
	-Dvapi=false \
	-Dglade=false \
	-Ddbg=false \
	-Dapp=false \
	-Da11y=false

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -delete

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/${PRGNAM}-gtk4-$VERSION-$ARCH-1_porteux.txz
