#!/bin/bash

PRGNAM=xfce4-xkb-plugin

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

DOWNLOADVERSION=$(curl -s https://gitlab.xfce.org/panel-plugins/${PRGNAM}/-/tags?format=atom | grep ' <title>' | grep -v pre | sort -V -r | head -1 | cut -d '>' -f 2 | cut -d '<' -f 1)
VERSION=$(echo $DOWNLOADVERSION | rev | cut -d '-' -f 1 | rev)
wget https://gitlab.xfce.org/panel-plugins/${PRGNAM}/-/archive/${DOWNLOADVERSION}/${PRGNAM}-${DOWNLOADVERSION}.tar.gz

tar xf $PRGNAM-$DOWNLOADVERSION.tar.?z*
cd $PRGNAM-$DOWNLOADVERSION

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS" \
meson setup \
	--prefix=/usr \
	--buildtype=release \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--libexecdir=/usr/libexec \
	--sysconfdir=/etc \
	--localstatedir=/var

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -delete

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
