#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=atril

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(get_latest_version_tag_from_github "mate-desktop" ${PRGNAM} "1.29")
wget https://github.com/mate-desktop/atril/archive/refs/tags/${VERSION}.tar.gz -O ${PRGNAM}-$VERSION.tar.gz

tar xf ${PRGNAM}-$VERSION.tar.?z
cd ${PRGNAM}-${VERSION//[vV]}

for i in $CWD/*.patch; do
	patch -p0 < $i;
done

sed -i "s|mate_desktop = dependency|#mate_desktop = dependency|g" meson.build
sed -i "s|mate_desktop,|#mate_desktop,|g" shell/meson.build
sed -i "s|subdir('help')|#subdir('help')|g" meson.build
sed -i "s|subdir('test')|mathjax_directory = ''|g" meson.build

sed -i '/^test_name =/,$d' backend/comics/meson.build
sed -i "s|comicsdocument.atril-backend.in|comicsdocument.atril-backend.desktop.in|g" backend/comics/meson.build
sed -i "s|'pixbuf.atril-backend.desktop.in'|'pixbufdocument.atril-backend.desktop.in'|g" backend/pixbuf/meson.build

sed -i "s|^gtk_x11.*|gtk_x11 = dependency('', required: false)|g" properties/meson.build
sed -i "s|^caja_extension.*|caja_extension = dependency('', required: false)|g" properties/meson.build

sed -i "s|^\(\s*version: \)'[0-9.]*',|\1'${VERSION//[vV]}',|" meson.build

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS" \
meson setup \
	--prefix=/usr \
	--buildtype=release \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--libexecdir=/usr/libexec \
	--sysconfdir=/etc \
	--localstatedir=/var \
	-Dintrospection=false \
	-Dt1lib=enabled \
	-Dpixbuf=enabled \
	-Dcomics=enabled \
	-Depub=disabled \
	-Dxps=disabled \
	-Dpreviewer=true \
	-Dgtk_unix_print=true

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -delete
rm -fr $PKG/usr/share/man

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-${VERSION//[vV]}-$ARCH-1_porteux.txz
