#!/bin/bash

PRGNAM=libadwaita

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(curl -s https://gitlab.gnome.org/GNOME/${PRGNAM}/-/tags?format=atom | grep -oPm 20 '(?<= <title>)[^<]+' | eval "${TESTRELEASES:-sort -Vr}" | head -1)
wget https://gitlab.gnome.org/GNOME/${PRGNAM}/-/archive/${VERSION}/${PRGNAM}-${VERSION}.tar.gz
[ ! -s ${PRGNAM}-${VERSION}.tar.gz ] && wget https://github.com/GNOME/${PRGNAM}/archive/refs/tags/$VERSION.tar.gz -O $PRGNAM-$VERSION.tar.gz

tar xf $PRGNAM-$VERSION.tar.?z
cd $PRGNAM-$VERSION

sed -i "s|'--doc-format=gi-docgen',||g" src/meson.build

sed -i "s|subdir('demo')|#subdir('demo')|g" meson.build
sed -i "s|subdir('examples')|#subdir('examples')|g" meson.build
sed -i "s|subdir('tests')|#subdir('tests')|g" meson.build
sed -i "s|subdir('doc')|#subdir('doc')|g" meson.build

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS" \
meson setup \
	--prefix=/usr \
	--datadir=/usr/share \
	--includedir=/usr/include \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--libexecdir=/usr/libexec \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--buildtype=release \
	-Ddocumentation=false \
	-Dexamples=false \
	-Dtests=false \
	-Dvapi=false \
	-Dprofiling=false

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -exec rm -f {} \;

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/${PRGNAM}-$VERSION-$ARCH-1_porteux.txz
