#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=cinnamon-settings-daemon

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "linuxmint" ${PRGNAM} "${TESTRELEASES}")
VERSION=${info#* }

tar xf $PRGNAM-$VERSION*.tar.?z
cd $PRGNAM-$VERSION*/

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS -Wno-incompatible-pointer-types" \
meson setup \
	--buildtype=release \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--localstatedir=/var \
	--prefix=/usr \
	--sysconfdir=/etc \
	-Duse_polkit=enabled \
	-Duse_logind=enabled \
	-Duse_cups=disabled \
	-Duse_smartcard=disabled \
	-Duse_color=disabled \
	-Duse_wacom=disabled \
	-Denable_debug=false \
	-Dgenerate_tz_coords=false

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -exec rm -f {} \;

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
