#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=cosmic-settings-daemon

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(download_master_from_github pop-os $PRGNAM) || exit 1
cd $PRGNAM-master || exit 1

for i in $CWD/*.patch; do
	patch -p1 < $i
done

RUSTFLAGS="${RUSTFLAGS/-Clto=fat/}"

sed 's/sudo/wheel/g' -i data/polkit-1/rules.d/cosmic-settings-daemon.rules
sed -i "s|prefix ?= /usr/local|prefix ?= /usr|g" Makefile

ls rust-toolchain* 1> /dev/null 2>&1 && rm rust-toolchain*
make -j${NUMBER_THREADS}
make install DESTDIR=$PKG

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-${ARCH}-1_porteux.txz
