#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=mate-session-manager

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "mate-desktop" $PRGNAM "1.29")
VERSION=${info#* }

tar xf $PRGNAM-$VERSION.tar.?z
cd $PRGNAM-$VERSION

CFLAGS="$GCC_CFLAGS -ffat-lto-objects" \
./configure \
	--prefix=/usr \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--libexecdir=/usr/libexec \
	--without-systemd \
	--with-elogind \
	--build=$ARCH-porteux-linux

make -j${NUMBER_THREADS} install-strip DESTDIR=$PKG

find $PKG -type f -name "*.la" -delete

install -Dm755 "$CWD/xinitrc.mate" $PKG/etc/X11/xinit/xinitrc.mate
cd $PKG/etc/X11/xinit/
cp -s xinitrc.mate xinitrc

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
