#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=lxhotkey

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

download_master_from_github lxde ${PRGNAM} || exit 1
cd ${PRGNAM}-master || exit 1

VERSION=$(grep -m1 -oP 'AC_INIT\(\s*\[?[^],]+\]?\s*,\s*\[?\K[^],\]]+' configure.ac)
if [ -z "$VERSION" ]; then
	echo "Error: cannot detect $PRGNAM version."
	exit 1
fi

./autogen.sh

CFLAGS="$GCC_CFLAGS" \
./configure \
	--prefix=/usr \
	--libdir=/usr/lib$SYSTEM_BITS \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--enable-gtk3 \
	--disable-static \
	--disable-man

make -j${NUMBER_THREADS} install-strip DESTDIR=$PKG

find $PKG -type f -name "*.la" -delete

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz