#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=openbox

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(download_master_from_github Mikachu openbox) || exit 1
cd openbox-master || exit 1

sed -i '1s|env python|env python3|' data/autostart/openbox-xdg-autostart

./bootstrap

sed -i 's|mkdirprog="\${MKDIRPROG-mkdir}"|mkdirprog="\${MKDIRPROG-mkdir} -p"|g' install-sh

CFLAGS="$GCC_CFLAGS" \
./configure \
	--prefix=/usr \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--enable-static=no

make -j${NUMBER_THREADS} install-strip DESTDIR=$PKG

find $PKG -type f -name "*.la" -exec rm -f {} \;

# gnome/kde session support and extra tools (previously stripped via patch)
rm -f $PKG/usr/bin/gdm-control
rm -f $PKG/usr/bin/gnome-panel-control
rm -f $PKG/usr/bin/obxprop
rm -f $PKG/usr/bin/openbox-gnome-session
rm -f $PKG/usr/bin/openbox-kde-session
rm -f $PKG/usr/share/xsessions/openbox-gnome.desktop
rm -f $PKG/usr/share/xsessions/openbox-kde.desktop
rm -fr $PKG/usr/share/gnome-session
rm -fr $PKG/usr/share/gnome

rm -fr $PKG/usr/share/doc
rm -fr $PKG/usr/share/man

install -Dm755 "$CWD/xinitrc.openbox" $PKG/etc/X11/xinit/xinitrc.openbox
cd $PKG/etc/X11/xinit/
cp -s xinitrc.openbox xinitrc

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz