#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=caja

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "mate-desktop" $PRGNAM "1.29")
VERSION=${info#* }

tar xf $PRGNAM-$VERSION.tar.?z
cd $PRGNAM-$VERSION

sed -i 's|docs \\|\\|g' Makefile.am
sed -i 's|test \\|\\|g' Makefile.am

CFLAGS="$GCC_CFLAGS -ffat-lto-objects" \
./configure \
	--prefix=/usr \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--disable-static \
	--libexecdir=/usr/libexec/caja \
	--disable-update-mimedb \
	--enable-introspection \
	--build=$ARCH-porteux-linux

make -j${NUMBER_THREADS} install-strip DESTDIR=$PKG

find $PKG -type f -name "*.la" -delete

# fix for invisible text cursor (caret) when renaming files
echo -e ".caja-desktop .entry,\n.caja-navigation-window .view .entry {\n    caret-color: #000000;\n}" >> $PKG/usr/share/caja/caja.css

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
