#!/bin/bash

PRGNAM=adwaita-cursors
PRGNAMDOWNLOAD=adwaita-icon-theme

CWD=$(dirname "$0")
TMP=$MODULEPATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(curl -s https://gitlab.gnome.org/GNOME/${PRGNAMDOWNLOAD}/-/tags?format=atom | grep -oPm 20 '(?<= <title>)[^<]+' | grep -v rc | grep -v alpha | grep -v beta | grep -v '\-dev' | sort -V -r | head -1)
wget https://gitlab.gnome.org/GNOME/${PRGNAMDOWNLOAD}/-/archive/${VERSION}/${PRGNAMDOWNLOAD}-${VERSION}.tar.gz

tar xfv $PRGNAMDOWNLOAD-$VERSION.tar.?z*
cd $PRGNAMDOWNLOAD-$VERSION

mkdir build && cd build
CFLAGS="$GCCFLAGS -flto=auto" \
meson setup \
	--buildtype=release \
	--infodir=/usr/info \
	--libdir=/usr/lib${SYSTEMBITS} \
	--localstatedir=/var \
	--mandir=/usr/man \
	--prefix=/usr \
	--sysconfdir=/etc \
	-Dstrip=true

DESTDIR=$PKG ninja -j${NUMBERTHREADS} install

rm -fr $PKG/usr/share/licenses

find $PKG/usr/share/icons/Adwaita -mindepth 1 -maxdepth 1 ! \( -name "cursors" \) -exec rm -rf '{}' \; 2>/dev/null

find $PKG -type f -name "*.la" -exec rm -f {} \;

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKGFLAGS} $MODULEPATH/packages/${PRGNAM}-$VERSION-$ARCH-1.txz
