#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=cjs

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "linuxmint" ${PRGNAM} "${TEST_RELEASES}")
VERSION=${info#* }

tar xf $PRGNAM-$VERSION*.tar.?z
cd $PRGNAM-$VERSION*/

sed -i "s|meson.build_root|meson.project_build_root|g" meson.build
sed -i "s|extra_args: '--warn-error'|fatal_warnings: get_option('werror')|g" meson.build

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS" \
CXXFLAGS="$GCC_CXXFLAGS" \
meson setup \
	--buildtype=release \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--localstatedir=/var \
	--prefix=/usr \
	--sysconfdir=/etc \
	-Dprofiler=disabled \
	-Dinstalled_tests=false \
	-Dskip_dbus_tests=true \
	-Dskip_gtk_tests=true
 
DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -delete
rm -fr $PKG/usr/libexec/installed-tests
rm -fr $PKG/usr/share/cjs-1.0

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
