#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=ffmpegthumbnailer

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "dirkvdb" ${PRGNAM} "ffmpegthumbnailer")
VERSION=${info#* }

tar xf ${PRGNAM}-${VERSION}.tar.?z
cd ${PRGNAM}-${VERSION}

cmake -B build -S . \
	-G Ninja \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_C_FLAGS="$GCC_CFLAGS" \
	-DCMAKE_CXX_FLAGS="$GCC_CXXFLAGS" \
	-DCMAKE_INSTALL_PREFIX="/usr" \
	-DCMAKE_INSTALL_LIBDIR=lib${SYSTEM_BITS} \
	-DENABLE_THUMBNAILER="yes" \
	-DENABLE_GIO="yes" \
	-DENABLE_TESTS="no"

DESTDIR=$PKG ninja -C build -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -exec rm -f {} \;

rm -fr $PKG/usr/share/man

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
