#!/bin/bash

PRGNAM=xfce4-power-manager

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

DOWNLOADVERSION=$(curl -s https://gitlab.xfce.org/xfce/${PRGNAM}/-/tags?format=atom | grep -oPm 20 '(?<= <title>)[^<]+' | grep -Ev '^xfce-|pre' | sort -Vr | {
	if [[ "$ALLOWTEST" == "yes" ]]; then
		head -1
	else
		while read -r version; do
			minor=$(echo "$version" | cut -d. -f2)
			if (( minor % 2 == 0 )); then
				echo "$version"
				break
			fi
		done
	fi
})
VERSION=$(echo $DOWNLOADVERSION | rev | cut -d '-' -f 1 | rev)
wget https://gitlab.xfce.org/xfce/${PRGNAM}/-/archive/${DOWNLOADVERSION}/${PRGNAM}-${DOWNLOADVERSION}.tar.gz

tar xf $PRGNAM-$DOWNLOADVERSION.tar.?z*
cd $PRGNAM-$DOWNLOADVERSION

if [ -f meson.build ]; then
	mkdir meson-build && cd meson-build
	CFLAGS="$GCC_CFLAGS -ffat-lto-objects -fPIC" \
	meson setup \
		--prefix=/usr \
		--buildtype=release \
		--libdir=/usr/lib${SYSTEM_BITS} \
		--libexecdir=/usr/libexec \
		--sysconfdir=/etc \
		--localstatedir=/var \
		-Dpolkit=disabled

	DESTDIR=$PKG ninja -j${NUMBER_THREADS} install
else
	CFLAGS="$GCC_CFLAGS -ffat-lto-objects -fPIC" \
	./autogen.sh \
		--prefix=/usr \
		--libdir=/usr/lib${SYSTEM_BITS} \
		--sysconfdir=/etc \
		--enable-shared=yes \
		--enable-static=no \
		--enable-debug=no \
		--enable-lto \
		--enable-wayland \
		--disable-network-manager \
		--build=$ARCH-porteux-linux

	make -j${NUMBER_THREADS} install-strip DESTDIR=$PKG
fi

find $PKG -type f -name "*.la" -exec rm -f {} \;

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
