#!/bin/bash

PRGNAM=mutter

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(curl -s https://gitlab.gnome.org/GNOME/${PRGNAM}/-/tags?format=atom | grep -oPm 20 '(?<= <title>)[^<]+'| eval "${TEST_RELEASES:-sort -Vr}" | head -1)
wget https://gitlab.gnome.org/GNOME/${PRGNAM}/-/archive/${VERSION}/${PRGNAM}-${VERSION}.tar.gz
[ ! -s ${PRGNAM}-${VERSION}.tar.gz ] && wget https://github.com/GNOME/${PRGNAM}/archive/refs/tags/$VERSION.tar.gz -O $PRGNAM-$VERSION.tar.gz

tar xf $PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION

sed -i "s|subdir('doc/man')||g" meson.build

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS" \
meson setup \
	--prefix=/usr \
	--buildtype=release \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--sysconfdir=/etc \
	--localstatedir=/var \
	-Ddefault_library=shared \
	-Dintrospection=true \
	-Dnative_backend=true \
	-Dstartup_notification=true \
	-Dudev=true \
	-Dwayland_eglstream=true \
	-Dclutter_tests=false \
	-Dcogl_tests=false \
	-Dmutter_tests=false \
	-Dinstalled_tests=false \
	-Ddocs=false \
	-Dprofiler=false \
	-Dbash_completion=false \
	-Ddevkit=disabled \
	-Dtests=disabled

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -delete

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/${PRGNAM}-$VERSION-$ARCH-1_porteux.txz
