#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=fastfetch

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "fastfetch-cli" ${PRGNAM})
VERSION=${info#* }

tar xf ${PRGNAM}-${VERSION}.tar.gz
cd ${PRGNAM}-${VERSION}

patch -p1 < $CWD/remove-external-display-label.patch

cmake -B build -S . \
	-G Ninja \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_C_FLAGS="$GCC_CFLAGS" \
	-DBUILD_FLASHFETCH=no \
	-DENABLE_OPENCL=off

DESTDIR="$PKG" ninja -C build install -j${NUMBER_THREADS}

echo -e "#!/bin/sh\nfastfetch --logo linux --color-title blue --color-keys blue -s Title:Separator:OS:Host:Kernel:Uptime:Packages:Shell:Display:DE:WM:WMTheme:Theme:Icons:Font:Cursor:Terminal:TerminalFont:CPU:GPU:Memory:Swap:LocalIp:Battery:PowerAdapter:Locale:Break:Colors \"\$@\"" > $PKG/usr/bin/neofetch
chmod 755 $PKG/usr/bin/neofetch

rm -fr "${PKG:?}/usr/share"

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz