#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=eom

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "mate-desktop" $PRGNAM "1.29")
VERSION=${info#* }

tar xf $PRGNAM-$VERSION.tar.?z
cd $PRGNAM-$VERSION

for i in $CWD/*.patch; do
	patch -p1 < $i
done

sed -i "s|subdir('doc')|#subdir('doc')|g" meson.build
sed -i "s|subdir('help')|#subdir('help')|g" meson.build
sed -i "s|subdir('man')|#subdir('man')|g" meson.build

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS -ffat-lto-objects" \
meson setup \
	--buildtype=release \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--localstatedir=/var \
	--prefix=/usr \
	--sysconfdir=/etc \
	-Dintrospection=disabled \
	-Dthumbnailer=disabled \
	-Dgdk-pixbuf-thumbnailer=disabled \
	-Dnls=disabled \
	-Dxmp=disabled

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -delete

sed -i "s|image/x-xpixmap|image/x-xpixmap;image/heic;image/jxl|g" $PKG/usr/share/applications/eom.desktop

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
