#!/bin/bash

PRGNAM=gnome-terminal

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION="3.48.1"
wget https://gitlab.gnome.org/GNOME/${PRGNAM}/-/archive/${VERSION}/${PRGNAM}-${VERSION}.tar.gz

tar xf $PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS" \
CXXFLAGS="$GCC_CXXFLAGS" \
meson setup \
	--prefix=/usr \
	--buildtype=release \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--libexecdir=/usr/libexec \
	--sysconfdir=/etc \
	--localstatedir=/var \
	-Dnautilus_extension=false \
	-Ddocs=false \
	-Dsearch_provider=false

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -exec rm -f {} \;

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
