#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=xviewer

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "linuxmint" ${PRGNAM} "${TESTRELEASES}")
VERSION=${info#* }

tar xf $PRGNAM-$VERSION.tar.?z
cd $PRGNAM-$VERSION

sed -i "s|subdir('help')|#subdir('help')|g" meson.build

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS" \
meson setup \
	--buildtype=release \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--localstatedir=/var \
	--prefix=/usr \
	--sysconfdir=/etc \
	-Ddocs=false \
	-Ddeprecated_warnings=false

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -exec rm -f {} \;
rm -fr $PKG/usr/share/xviewer/gir-1.0

sed -i "s|image/jpg|image/jpg;image/jxl|g" $PKG/usr/share/applications/xviewer.desktop

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
