#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=libjxl

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(download_master_from_github libjxl libjxl main) || exit 1
cd libjxl-main || exit 1

# skipping not used deps download
sed -i "s|download_github testdata libjxl/testdata||g" deps.sh
sed -i "s|download_github third_party/brotli google/brotli||g" deps.sh
sed -i "s|download_github third_party/sjpeg webmproject/sjpeg||g" deps.sh
sed -i "s|download_github third_party/zlib madler/zlib||g" deps.sh
sed -i "s|download_github third_party/libpng glennrp/libpng||g" deps.sh
sed -i "s|download_github third_party/libjpeg-turbo libjpeg-turbo/libjpeg-turbo||g" deps.sh

sh deps.sh

LDFLAGS="$LLDFLAGS" \
cmake -B build -S . \
	-G Ninja \
	-DBUILD_TESTING=false \
	-DENABLE_FUZZERS_DEFAULT=false \
	-DCMAKE_C_FLAGS="$CLANG_CFLAGS" \
	-DCMAKE_CXX_FLAGS="$CLANG_CXXFLAGS" \
	-DBUNDLE_LIBPNG_DEFAULT='NO' \
	-DCMAKE_BUILD_TYPE='Release' \
	-DCMAKE_INSTALL_PREFIX='/usr' \
	-DCMAKE_INSTALL_LIBDIR=lib${SYSTEM_BITS} \
	-DCMAKE_INSTALL_BINDIR=/usr/bin \
	-DBUILD_SHARED_LIBS=true \
	-DJPEGXL_ENABLE_JNI=false \
	-DJPEGXL_ENABLE_DEVTOOLS=false \
	-DJPEGXL_ENABLE_DOXYGEN=false \
	-DJPEGXL_ENABLE_MANPAGES=false \
	-DJPEGXL_ENABLE_SKCMS=false \
	-DJPEGXL_ENABLE_BENCHMARK=false \
	-DJPEGXL_ENABLE_EXAMPLES=false \
	-DJPEGXL_ENABLE_FUZZERS=false \
	-DJPEGXL_ENABLE_PLUGINS=true \
	-DJPEGXL_ENABLE_VIEWERS=false \
	-DJPEGXL_ENABLE_TOOLS=false \
	-DJPEGXL_ENABLE_TCMALLOC=false \
	-DJPEGXL_WARNINGS_AS_ERRORS=false \
	-DJPEGXL_FORCE_SYSTEM_BROTLI=false \
	-DJPEGXL_FORCE_SYSTEM_HWY=false \
	-DJPEGXL_FORCE_SYSTEM_LCMS2=false \
	-DJPEGXL_ENABLE_SJPEG=false \
	-DJPEGXL_STATIC=false \
	-DCMAKE_C_COMPILER=clang \
	-DCMAKE_CXX_COMPILER=clang++

DESTDIR=$PKG ninja -C build -j${NUMBER_THREADS} install

find $PKG -type f -name "*.a" -exec rm -f {} \;
find $PKG -type f -name "*.la" -delete
find $PKG -name perllocal.pod -o -name ".packlist" -o -name "*.bs" | xargs rm -f || true

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
