#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=xcape

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "fulalas" ${PRGNAM})
VERSION=${info#* }

tar xf ${PRGNAM}-${VERSION}.tar.?z
cd ${PRGNAM}-${VERSION}

CFLAGS="$GCC_CFLAGS" \
make -j${NUMBER_THREADS}
make install -j${NUMBER_THREADS} MANDIR=/man DESTDIR=$PKG

find $PKG -type f -name "*.a" -exec rm -f {} \;
rm -fr $PKG/usr/man

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz