#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=xfwm4-gl

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

download_master_from_github fulalas $PRGNAM main || exit 1
cd xfwm4-gl-main

VERSION=$(sed -n 's/^XDT_VERSION_INIT(\[\([^]]*\)\]\(, *\[\([^]]*\)\]\)\?).*/\1\3/p' configure.ac)
if [ -z "$VERSION" ]; then
	echo "Error: cannot detect $PRGNAM version."
	exit 1
fi

CFLAGS="$GCC_CFLAGS -ffat-lto-objects -ffast-math" \
./autogen.sh \
	--prefix=/usr \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--sysconfdir=/etc \
	--disable-static \
	--disable-debug \
	--enable-epoxy \
	--enable-xpresent \
	--build=$ARCH-porteux-linux

make -j${NUMBER_THREADS} install-strip DESTDIR=$PKG

find $PKG -type f -name "*.la" -delete

# fix cropping title bar when maximized
sed -i "s|^frame_border_top=.*|frame_border_top=0|" $PKG/usr/share/themes/Default*/xfwm4/themerc

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
