#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=transmission

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github ${PRGNAM} ${PRGNAM})
VERSION=${info#* }

tar xf $PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION

patch -p1 < $CWD/fix-crash-on-download-complete.patch

cmake -B build -S . \
	-G Ninja \
	-DCMAKE_C_FLAGS="${GCC_CFLAGS} -fPIC -ffat-lto-objects" \
	-DCMAKE_CXX_FLAGS="${GCC_CXXFLAGS} -ffat-lto-objects" \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=lib${SYSTEM_BITS} \
	-DRUN_CLANG_TIDY=OFF \
	-DENABLE_TESTS=OFF \
	-DWITH_APPINDICATOR=OFF \
	-DENABLE_QT=OFF \
	-DINSTALL_DOC=OFF

cmake --build build -j${NUMBER_THREADS}
DESTDIR=$PKG ninja -C build -j${NUMBER_THREADS} install

rm -fr $PKG/usr/share/man

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz