#!/bin/sh

for arg in "$@"; do
	case "$arg" in
		--force-setup)
			RESET="true"
			shift
			break
			;;
	esac
done

is_root() {
	groupsList=$(groups)

	for entry in $groupsList; do
		if [[ "$entry" == "root" ]]; then
			return 0
		fi
	done

	return 1
}

if [ -z "$RESET" ] && [ -L "/var/lib/flatpak" ] && [ -e "$(readlink -f /var/lib/flatpak)" ]; then
	[[ " $* " == *" run "* ]] && is_root && echo "To run installed flatpak applications don't use sudo/root." && exit 1

	# Required because flatpak module might be activated after boot so xdg-desktop-portal wouldn't be aware of xdg-desktop-portal-gtk
	if command -v /usr/libexec/xdg-desktop-portal >/dev/null; then
		setsid /usr/libexec/xdg-desktop-portal -r > /dev/null 2>&1 &
	fi

	exec flatpak_ "${@}"
	exit 0
fi

FLATPAK_STORAGE_PATH="$1"

if [ -z "$FLATPAK_STORAGE_PATH" ] || [ ! -d "$FLATPAK_STORAGE_PATH" ]; then
	echo "First time running flatpak requires a valid POSIX path"
	echo "to store flatpak files."
	echo
	echo "example: flatpak /mnt/sda1"
	echo "example: flatpak --force-setup /mnt/nvme0n1p2/"
	exit 1
fi

fail() {
	echo "Partition is not POSIX-compliant or you don't have write permission."
	rm -rf "$TMP" 2>/dev/null
	exit 1
}

check_posix() {
	# Test 1: ntfs is still not fully POSIX-compliant
	if command -v findmnt >/dev/null; then
		current_partition=$(findmnt -no FSTYPE "$FLATPAK_STORAGE_PATH")
		[[ "$current_partition" == *fat* ]] && fail
		[[ "$current_partition" == *ntfs* ]] && fail
	fi

	# Test 2: folder creation
	TMP="$FLATPAK_STORAGE_PATH/.posix_test_$$"
	mkdir "$TMP" 2>/dev/null || fail

	# Test 3: permissions
	touch "$TMP/file" || fail
	chmod 600 "$TMP/file" 2>/dev/null || fail

	# Test 4: symlinks
	ln -s file "$TMP/link" 2>/dev/null || fail

	# Test 5: hard links
	ln "$TMP/file" "$TMP/hardlink" 2>/dev/null || fail

	# Test 6: fifo
	mkfifo "$TMP/fifo" 2>/dev/null || fail

	# Test 7: timestamps
	touch -t 200001010101 "$TMP/file" 2>/dev/null
	[ $? -eq 0 ] || fail

	# Clean up
	rm -rf "$TMP" 2>/dev/null
}

! is_root && echo "Flatpak setup requires admin's right." && exit 1

check_posix

# Create main symlink
mkdir -p "$FLATPAK_STORAGE_PATH"/flatpak
ln -sf "$FLATPAK_STORAGE_PATH"/flatpak /var/lib/

# Add flathub and update
flatpak_ remote-add flathub https://flathub.org/repo/flathub.flatpakrepo > /dev/null 2>&1
flatpak_ update --appstream

echo -e "\n\e[93mIf Flatpak module was activated after boot, applications installed"
echo -e "\e[93mwith it will appear on the desktop in the next login.\e[0m"

echo -e "\n\e[36mAll set. You can now use flatpak normally.\e[0m"
