#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=audacious-plugins

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "audacious-media-player" ${PRGNAM})
VERSION=${info#* }

if [[ ${QT} == "5" ]]; then
	TOOLKIT="qt5"
	toolkitFlags="-Dgtk=false -Dqt5=true"
elif [[ ${QT} == "6" ]]; then
	TOOLKIT="qt6"
	toolkitFlags="-Dgtk=false -Dqt=true"
else
	TOOLKIT="gtk3"
	toolkitFlags="-Dgtk=true -Dqt5=false -Dqt=false"
fi

tar xf ${PRGNAM}-${PRGNAM}-$VERSION.tar.?z
cd ${PRGNAM}-${PRGNAM}-$VERSION

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS" \
CXXFLAGS="$GCC_CXXFLAGS" \
meson setup \
	--buildtype=release \
	--prefix=/usr \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--sysconfdir=/etc \
	-Dneon=false \
	${toolkitFlags}

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -delete

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$TOOLKIT-$VERSION-$ARCH-1_porteux.txz
