#!/bin/bash

PRGNAM=geocode-glib

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

wget https://gitlab.gnome.org/GNOME/${PRGNAM}/-/archive/master/${PRGNAM}-master.tar.gz
tar xf ${PRGNAM}-master.tar.?z*
cd ${PRGNAM}-master
VERSION=$(date -r . +%Y%m%d)

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS" \
meson setup \
	--buildtype=release \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--localstatedir=/var \
	--prefix=/usr \
	--sysconfdir=/etc \
	-Dstrip=true \
	-Denable-introspection=true \
	-Denable-gtk-doc=false \
	-Denable-installed-tests=false \
	-Dsoup2=false

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -delete

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/${PRGNAM}-$VERSION-$ARCH-1_porteux.txz
