#!/bin/bash

killall -ew pipewire > /dev/null 2>&1
pipewire &

# Wait for pipewire to load
sleepTimes=50
while [ $sleepTimes -gt 0 ] && ! pgrep -x "pipewire" > /dev/null; do
	sleep 0.2
	sleepTimes=$((sleepTimes - 1))
done

killall -ew wireplumber > /dev/null 2>&1
wireplumber &

killall -ew pipewire-pulse > /dev/null 2>&1
pipewire-pulse &
