#!/bin/sh

if ! pgrep -x "pipewire" > /dev/null; then
	pipewire &
fi

# Wait for pipewire to load
sleepTimes=50
while [ $sleepTimes -gt 0 ] && ! pgrep -x "pipewire" > /dev/null; do
	sleep 0.2
	sleepTimes=$((sleepTimes - 1))
done

if ! pgrep -x "wireplumber" > /dev/null; then
	wireplumber &
fi

if ! pgrep -x "pipewire-pulse" > /dev/null; then
	pipewire-pulse &
fi
