#!/bin/sh

! pgrep -x "pipewire" > /dev/null && pipewire &

# Wait for pipewire to load
sleepTimes=50
while [ $sleepTimes -gt 0 ] && ! pgrep -x "pipewire" > /dev/null; do
	sleep 0.2
	let sleepTimes=sleepTimes-1
done

! pgrep -x "wireplumber" > /dev/null && wireplumber &
! pgrep -x "pipewire-pulse" > /dev/null && pipewire-pulse &
