#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=cosmic-comp

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(download_master_from_github pop-os $PRGNAM) || exit 1
cd $PRGNAM-master || exit 1

RUSTFLAGS="${RUSTFLAGS/-Clto=fat/}"

sed -i "s|prefix ?= /usr/local|prefix ?= /usr|g" Makefile

download_master_from_github fulalas libdisplay-info-pure || exit 1
bash libdisplay-info-pure/apply.sh . || exit 1

ls rust-toolchain* 1> /dev/null 2>&1 && rm rust-toolchain*
make -j${NUMBER_THREADS}
make install DESTDIR=$PKG

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-${ARCH}-1_porteux.txz
