#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=xdg-desktop-portal

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(get_latest_version_tag_from_github "flatpak" ${PRGNAM})
versions_to_ignore="${VERSION}"
minor_version=$(echo "$VERSION" | cut -d. -f2)

while (( ${minor_version} % 2 == 1 )); do
	VERSION=$(get_latest_version_tag_from_github "flatpak" ${PRGNAM} "${versions_to_ignore}|${VERSION}")
	versions_to_ignore="${versions_to_ignore}|${VERSION}"
	minor_version=$(echo "$VERSION" | cut -d. -f2)
done

wget https://github.com/flatpak/${PRGNAM}/releases/download/${VERSION}/${PRGNAM}-${VERSION}.tar.xz

tar xf $PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS" \
meson setup \
	--prefix=/usr \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--libexecdir=/usr/libexec \
	--bindir=/usr/bin \
	--sbindir=/usr/sbin \
	--includedir=/usr/include \
	--datadir=/usr/share \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--buildtype=release \
	-Ddocumentation=disabled \
	-Dtests=disabled \
	-Dsandboxed-image-validation=disabled \
	-Dsandboxed-sound-validation=disabled \
	-Dflatpak-interfaces=disabled \
	-Dgeoclue=disabled \
	-Dsystemd=disabled \
	-Dman-pages=disabled

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -delete

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz