#!/bin/bash

PRGNAM=xfce4-dev-tools

CWD=$(dirname "$0")
TMP=${TMP:-$MODULEPATH/$PRGNAM}
PKG=$TMP/package-$PRGNAM

set -e

rm -rf $PKG
mkdir -p $TMP $PKG
cd $TMP
rm -rf $PRGNAM-*

wget -r -nd --no-parent $SOURCEREPOSITORY/xfce/$PRGNAM/ -A $PRGNAM-*
VERSION=${VERSION:-$(echo $PRGNAM-*.tar.?z* | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}

SLKCFLAGS="$GCCFLAGS -feliminate-unused-debug-types -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z -Wl,now -Wl,-z -Wl,relro -fno-semantic-interposition -ffat-lto-objects -fno-trapping-math -Wl,-sort-common -Wl,--enable-new-dtags -flto -fuse-linker-plugin -fwhole-program"

tar xvf $PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION

CFLAGS="$SLKCFLAGS" \
./configure \
    --prefix=/usr \
    --libdir=/usr/lib${SYSTEMBITS} \
    --sysconfdir=/etc \
    --mandir=/usr/man \
    --docdir=/usr/doc/$PRGNAM-$VERSION \
    --disable-static \
    --disable-debug \
    --build=$ARCH-porteux-linux

make -j${NUMBERTHREADS} install DESTDIR=$PKG

find $PKG -type f -name "*.la" -exec rm -f {} \;

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $MODULEPATH/packages/$PRGNAM-$VERSION-$ARCH-1.txz
