#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=mate-panel

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

info=$(download_latest_from_github "mate-desktop" $PRGNAM "1.29")
VERSION=${info#* }

tar xf $PRGNAM-$VERSION.tar.?z
cd $PRGNAM-$VERSION

sed -i 's|YELP_HELP_INIT||g' configure.ac
sed -i 's|yelp-build|ls|g' autogen.sh
sed -i 's|doc\t.*|\\|g' Makefile.am
sed -i 's|help\t.*|\\|g' Makefile.am

CFLAGS="$GCC_CFLAGS -ffat-lto-objects" \
./autogen.sh \
	--prefix=/usr \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--disable-static \
	--libexecdir=/usr/libexec/mate-panel \
	--enable-introspection=yes \
	--enable-x11 \
	--enable-wayland \
	--disable-gtk-doc \
	--build=$ARCH-porteux-linux

make -j${NUMBER_THREADS} install-strip DESTDIR=$PKG

find $PKG -type f -name "*.la" -exec rm -f {} \;

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
