#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=kora

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(download_master_from_github bikass kora) || exit 1
cd kora-master || exit 1

# this icon breaks our xzm icon, so we need to remove it
rm ${PRGNAM}/apps/scalable/application.svg

dest_dir="$PKG/usr/share/icons/${PRGNAM}"
mkdir -p "$dest_dir"
rm -f "${PRGNAM}/create-new-icon-theme.cache.sh"
cp -r "${PRGNAM}/"* "$dest_dir"
gtk-update-icon-cache -f "$dest_dir"

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/${PRGNAM}-icon-theme-$VERSION-noarch-1_porteux.txz > /dev/null 2>&1