#!/bin/bash

source "$BUILDER_UTILS_PATH/latest-from-github.sh"

PRGNAM=ntfsprogs-plus

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION=$(download_master_from_github ntfsprogs-plus ntfsprogs-plus main) || exit 1
cd ntfsprogs-plus-main || exit 1

# only create lost+found folder when finding orphan files
patch -p1 < $CWD/fix-lost-found-folder.patch

./autogen.sh

CFLAGS="$GCC_CFLAGS -ffat-lto-objects" \
./configure \
	--prefix=/usr \
	--libdir=/usr/lib$SYSTEM_BITS \
	--localstatedir=/var \
	--disable-static \
	--disable-extras \
	--disable-dependency-tracking

make -j${NUMBER_THREADS} install-strip DESTDIR=$PKG

find $PKG -type f -name "*.la" -exec rm -f {} \;

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz