#!/bin/bash

PRGNAM=file-roller

CWD=$(dirname "$0")
TMP=$MODULE_PATH/$PRGNAM
PKG=$TMP/package-$PRGNAM

set -e

[ -e $TMP ] && rm -rf $TMP
mkdir -p $TMP $PKG
cd $TMP

VERSION="3.42.0"
wget https://gitlab.gnome.org/GNOME/${PRGNAM}/-/archive/${VERSION}/${PRGNAM}-${VERSION}.tar.gz

tar xf $PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION

sed -i "s|subdir('help')|#subdir('help')|g" meson.build

mkdir meson-build && cd meson-build
CFLAGS="$GCC_CFLAGS" \
meson setup \
	--prefix=/usr \
	--buildtype=release \
	--libdir=/usr/lib${SYSTEM_BITS} \
	--libexecdir=/usr/libexec \
	--sysconfdir=/etc \
	--localstatedir=/var \
	-Ddefault_library=shared \
	-Drun-in-place=false \
	-Dnautilus-actions=disabled \
	-Dnotification=enabled \
	-Dpackagekit=false \
	-Dlibarchive=enabled

DESTDIR=$PKG ninja -j${NUMBER_THREADS} install

find $PKG -type f -name "*.la" -delete
rm $PKG/usr/share/dbus-1/services/org.gnome.ArchiveManager1.service
rm $PKG/usr/share/dbus-1/services/org.gnome.FileRoller.service

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg ${MAKEPKG_FLAGS} $MODULE_PATH/packages/$PRGNAM-$VERSION-$ARCH-1_porteux.txz
